FROM public.ecr.aws/lambda/python:3.11

# Install your full pricing dependencies
COPY requirements.txt ./
RUN pip install --upgrade pip \
 && pip install --no-cache-dir -r requirements.txt


# Copy worker and your shared modules
COPY worker.py models.py monte_carlo.py ./

# Lambda entrypoint
CMD ["worker.lambda_handler"]
